const String title = 'CHEGOU NOSSO TEMPO DE HOJE MANIFESTAR-SE DE MANEIRA '
    'A ULTRAPASSAR OS LIMITES.\n\n'
  'NÃO CABE MAIS EM NÓS, NÃO PODEMOS MAIS NOS CONTER.\n'
  'ESTAMOS CHEIOS. CHEIOS E PRONTOS PARA TRANSBORDAR!\n\n'
  'INVISTA NESSE TEMPO E MERGULHE MAIS FUNDO PARA VIVER O QUE NUNCA VIVEU ANTES. '
  'SERÃO DOIS DIAS DE CONHECIMENTO PROFUNDO DA PALAVRA ATRAVÉS DE PASTORES '
  'NACIONAIS E INTERNACIONAIS QUE TEM SE LEVANTADO COMO UMA VOZ PROFÉTICA NA '
  'NOSSA GERAÇÃO.\n\n'
  'SESSÕES ESPECÍFICAS PARA TE FAZER VIVER UM NOVO NÍVEL EM TODAS AS ÁREAS '
  'DA SUA VIDA E ALÉM DE SERMOS CONDUZIDOS'
  'ATRAVÉS DOS MINISTROS DA ADORAÇÃO, A EXALTAÇÃO DO NOSSO SENHOR JESUS!\n\n'
  'ALÉM DA NOSSA CONFERÊNCIA TRANSBORDAR SERVIR COMO UM BRAÇO DE APOIO PARA O '
  'NOSSO PROJETO TRANSBORDAR, A CONFERÊNCIA ALIMENTA TAMBÉM O ESPIRITUAL. '
  'VIVEMOS DOIS DIAS DE IMERSÃO EM UM AMBIENTE PROFÉTICO ONDE PALAVRAS DE CURA, '
  'DE FÉ E PROFÉTICAS SÃO LIBERADAS, PESSOAS SÃO TRANSFORMADAS E DESTINOS '
  'SÃO DESTRAVADOS.';

final faQuestions = {
  "QUAIS DIAS IRÃO ACONTECER A CONFERÊNCIA TRANSBORDAR?" : "DIAS 21 E 22 DE "
      "ABRIL (FERIADO DE SEXTA E SÁBADO)",
  "QUAIS SERÃO OS HORÁRIOS?": "",
  "ESPAÇO KIDS, TERÁ PROGRAMAÇÃO PARA AS CRIANÇAS?" : "",
  "CRIANÇAS PODEM ENTRAR NA CONFERÊNCIA TRANSBORDAR?" : "",
  "CRIANÇAS DE 12 A 13 ANOS, PODERÃO PARTICIPAR DA CONFERÊNCIA?": "",
  "OS ASSENTOS SERÃO RESERVADOS?" : "",
  "TEM INDICAÇÕES DE HOTÉIS?" : "",
  "COMO FUNCIONARA A ALIMENTAÇÃO?" : "",
  "COMO FAÇO PARA RETIRAR MINHA PULSEIRA?" : "",
  "POSSO COMPRAR INGRESSO PARA UM DIA?" : ""
};