const String title = 'CHEGOU NOSSO TEMPO DE HOJE MANIFESTAR-SE DE MANEIRA '
    'A ULTRAPASSAR OS LIMITES.\n\n'
  'NÃO CABE MAIS EM NÓS, NÃO PODEMOS MAIS NOS CONTER.\n'
  'ESTAMOS CHEIOS. CHEIOS E PRONTOS PARA TRANSBORDAR!\n\n'
  'INVISTA NESSE TEMPO E MERGULHE MAIS FUNDO PARA VIVER O QUE NUNCA VIVEU ANTES. '
  'SERÃO DOIS DIAS DE CONHECIMENTO PROFUNDO DA PALAVRA ATRAVÉS DE PASTORES '
  'NACIONAIS E INTERNACIONAIS QUE TEM SE LEVANTADO COMO UMA VOZ PROFÉTICA NA '
  'NOSSA GERAÇÃO.\n\n'
  'SESSÕES ESPECÍFICAS PARA TE FAZER VIVER UM NOVO NÍVEL EM TODAS AS ÁREAS '
  'DA SUA VIDA E ALÉM DE SERMOS CONDUZIDOS'
  'ATRAVÉS DOS MINISTROS DA ADORAÇÃO, A EXALTAÇÃO DO NOSSO SENHOR JESUS!\n\n'
  'ALÉM DA NOSSA CONFERÊNCIA TRANSBORDAR SERVIR COMO UM BRAÇO DE APOIO PARA O '
  'NOSSO PROJETO TRANSBORDAR, A CONFERÊNCIA ALIMENTA TAMBÉM O ESPIRITUAL. '
  'VIVEMOS DOIS DIAS DE IMERSÃO EM UM AMBIENTE PROFÉTICO ONDE PALAVRAS DE CURA, '
  'DE FÉ E PROFÉTICAS SÃO LIBERADAS, PESSOAS SÃO TRANSFORMADAS E DESTINOS '
  'SÃO DESTRAVADOS.';

final faQuestions = {
  "QUAIS DIAS IRÃO ACONTECER A CONFERÊNCIA TRANSBORDAR?" : "DIAS 21 E 22 DE "
      "ABRIL. (FERIADO DE SEXTA E SÁBADO)",
  "QUAIS SERÃO OS HORÁRIOS?": "DIA 21/04 - O HORÁRIO DO CHECK-IN SERÁ ÀS 07H30.",
  "ESPAÇO KIDS, TERÁ PROGRAMAÇÃO PARA AS CRIANÇAS?" : "SIM, TEREMOS UMA "
      "PROGRAMAÇÃO ESPECIAL PARA AS CRIANÇAS NA CENTRAL KIDS. CRIANÇAS DE 03 "
      "À 11 ANOS.",
  "CRIANÇAS PODEM ENTRAR NA CONFERÊNCIA TRANSBORDAR?" : "NÃO PODERÃO ENTRAR NA "
      "ÁREA DA CONFERÊNCIA TRANSBORDAR. TEREMOS PROGRAMAÇÃO ESPECIAL PARA ELAS "
      "NA CENTRAL KIDS.",
  "CRIANÇAS DE 12 A 13 ANOS, PODERÃO PARTICIPAR DA CONFERÊNCIA?": "SIM, 12 E 13 "
      "ANOS PAGARÃO 50% DO VALOR DO INGRESSO.",
  "OS ASSENTOS SERÃO RESERVADOS?" : "NÃO. OS ASSENTOS SERÃO DISPONIBILIZADOS "
      "MEDIANTE A ORDEM DE CHEGADA. NÃO SERÃO RESERVADOS E ESTÁ PROIBIDO "
      "RESERVAR OU GUARDAR LUGAR.",
  "TEM INDICAÇÕES DE HOTÉIS?" : "NITERÓI PALACE HOTEL: RUA GENERAL ANDRADE "
    "NEVES, 134 - INGÁ - NITERÓI.\n"
    "HOTEL SOLAR DO AMANHECER: AV. PREFEITO SILVIO PICANÇO, 839 - CHARITAS - NITERÓI.\n"
    "MATIZ NITERÓI DESIGN HOTEL: RUA JOAQUIM TÁVORA, 54 - ICARAÍ - NITERÓI.\n"
    "HOTEL DOM QUIXOTE: R. CMTE. ARI PARREIRAS, 1381 - PARAÍSO - SÃO GONÇALO.",
  "COMO FUNCIONARA A ALIMENTAÇÃO?" : "TEREMOS UMA PRAÇA DE ALIMENTAÇÃO DISPONÍVEL "
      "COM DIVERSAS OPÇÕES GASTRONÔMICAS. E TAMBÉM NOSSA CENTRAL COFFEE ESTARÁ "
      "ABERTA DURANTE TODO O EVENTO.",
  "COMO FAÇO PARA RETIRAR MINHA PULSEIRA?" : "A RETIRADA DAS PULSEIRAS DA "
      "CONFERÊNCIA TRANSBORDAR INICIARÃO NO DIA DO EVENTO, NO HORÁRIO DO "
      "CHECK-IN. (PARA VERIFICAR HORÁRIO, CONSULTE O PRIMEIRO ITEM).",
  "POSSO COMPRAR INGRESSO PARA UM DIA?" : "NÃO, A COMPRA DO INGRESSO É VÁLIDA "
      "PARA OS DOIS DIAS DE CONFERÊNCIA TRANSBORDAR."
};